### ISSUE TITLE
The "Whos Next" overlay styles have changed

### ISSUE THREAD

**Issue by DR-DinoMight** [whitep4nth3r/theclaw.team#20]
**Describe the bug**
It seems that the styles used for the avatars on the "Whos Next" overlay have changed, and are now round with a black box appearing see image 

**To Reproduce**
1. Go to 'Whos Next overlay'
2. See a visual error

**Expected behavior**
The Avatar should be square and the black box shouldn't appear

**Screenshots**
![Example of broken styles](https://user-images.githubusercontent.com/1541665/148293797-47393251-f348-4ae7-95e2-ed31bab08502.png)

**Comment by DR-DinoMight** [comment]
Will look at this if you want to assign it to me

**Comment by whitep4nth3r** [comment]
Ah yes, this was to do with the redesign from iBaldie! Will assign to you. Thanks for finding it!
